//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://smev.gosuslugi.ru/rev120315", ConfigurationName="Service.SmevBindingExtSevice")]
    public interface SmevBindingExtSevice {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://smev.gosuslugi.ru/rev120315/SmevBindingExtSevice/DoWork", ReplyAction="http://smev.gosuslugi.ru/rev120315/SmevBindingExtSevice/DoWorkResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.Service.Response DoWork(Client.Service.Request request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://smev.gosuslugi.ru/rev120315/SmevBindingExtSevice/DoWork", ReplyAction="http://smev.gosuslugi.ru/rev120315/SmevBindingExtSevice/DoWorkResponse")]
        System.Threading.Tasks.Task<Client.Service.Response> DoWorkAsync(Client.Service.Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smev.gosuslugi.ru/rev120315")]
    public partial class MessageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private orgExternalType senderField;
        
        private orgExternalType recipientField;
        
        private orgExternalType originatorField;
        
        private object itemField;
        
        private TypeCodeType typeCodeField;
        
        private StatusType statusField;
        
        private System.DateTime dateField;
        
        private string exchangeTypeField;
        
        private string requestIdRefField;
        
        private string originRequestIdRefField;
        
        private string serviceCodeField;
        
        private string caseNumberField;
        
        private SubMessageType[] subMessagesField;
        
        private string testMsgField;
        
        private string oKTMOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public orgExternalType Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public orgExternalType Recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("Recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public orgExternalType Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
                this.RaisePropertyChanged("Originator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Service", typeof(ServiceType), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("ServiceName", typeof(string), Order=3)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TypeCodeType TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ExchangeType {
            get {
                return this.exchangeTypeField;
            }
            set {
                this.exchangeTypeField = value;
                this.RaisePropertyChanged("ExchangeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string RequestIdRef {
            get {
                return this.requestIdRefField;
            }
            set {
                this.requestIdRefField = value;
                this.RaisePropertyChanged("RequestIdRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OriginRequestIdRef {
            get {
                return this.originRequestIdRefField;
            }
            set {
                this.originRequestIdRefField = value;
                this.RaisePropertyChanged("OriginRequestIdRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("ServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CaseNumber {
            get {
                return this.caseNumberField;
            }
            set {
                this.caseNumberField = value;
                this.RaisePropertyChanged("CaseNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubMessage", IsNullable=false)]
        public SubMessageType[] SubMessages {
            get {
                return this.subMessagesField;
            }
            set {
                this.subMessagesField = value;
                this.RaisePropertyChanged("SubMessages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TestMsg {
            get {
                return this.testMsgField;
            }
            set {
                this.testMsgField = value;
                this.RaisePropertyChanged("TestMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string OKTMO {
            get {
                return this.oKTMOField;
            }
            set {
                this.oKTMOField = value;
                this.RaisePropertyChanged("OKTMO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smev.gosuslugi.ru/rev120315")]
    public partial class orgExternalType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2004/08/xop/include")]
    public partial class Include : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private string hrefField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
                this.RaisePropertyChanged("href");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smev.gosuslugi.ru/rev120315")]
    public partial class ReferenceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Include includeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2004/08/xop/include", Order=0)]
        public Include Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
                this.RaisePropertyChanged("Include");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smev.gosuslugi.ru/rev120315")]
    public partial class AppDocumentType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string requestCodeField;
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestCode {
            get {
                return this.requestCodeField;
            }
            set {
                this.requestCodeField = value;
                this.RaisePropertyChanged("RequestCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BinaryData", typeof(byte[]), DataType="base64Binary", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("DigestValue", typeof(byte[]), DataType="base64Binary", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Reference", typeof(ReferenceType), Order=1)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=2)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
                this.RaisePropertyChanged("ItemsElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smev.gosuslugi.ru/rev120315", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        BinaryData,
        
        /// <remarks/>
        DigestValue,
        
        /// <remarks/>
        Reference,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smev.gosuslugi.ru/rev120315")]
    public partial class AppDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smev.gosuslugi.ru/rev120315")]
    public partial class MessageDataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AppDataType appDataField;
        
        private AppDocumentType appDocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AppDataType AppData {
            get {
                return this.appDataField;
            }
            set {
                this.appDataField = value;
                this.RaisePropertyChanged("AppData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AppDocumentType AppDocument {
            get {
                return this.appDocumentField;
            }
            set {
                this.appDocumentField = value;
                this.RaisePropertyChanged("AppDocument");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smev.gosuslugi.ru/rev120315")]
    public partial class SubMessageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subRequestNumberField;
        
        private StatusType statusField;
        
        private orgExternalType originatorField;
        
        private System.DateTime dateField;
        
        private string requestIdRefField;
        
        private string originRequestIdRefField;
        
        private string serviceCodeField;
        
        private string caseNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubRequestNumber {
            get {
                return this.subRequestNumberField;
            }
            set {
                this.subRequestNumberField = value;
                this.RaisePropertyChanged("SubRequestNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public orgExternalType Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
                this.RaisePropertyChanged("Originator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RequestIdRef {
            get {
                return this.requestIdRefField;
            }
            set {
                this.requestIdRefField = value;
                this.RaisePropertyChanged("RequestIdRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OriginRequestIdRef {
            get {
                return this.originRequestIdRefField;
            }
            set {
                this.originRequestIdRefField = value;
                this.RaisePropertyChanged("OriginRequestIdRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ServiceCode {
            get {
                return this.serviceCodeField;
            }
            set {
                this.serviceCodeField = value;
                this.RaisePropertyChanged("ServiceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CaseNumber {
            get {
                return this.caseNumberField;
            }
            set {
                this.caseNumberField = value;
                this.RaisePropertyChanged("CaseNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smev.gosuslugi.ru/rev120315")]
    public enum StatusType {
        
        /// <remarks/>
        REQUEST,
        
        /// <remarks/>
        RESULT,
        
        /// <remarks/>
        REJECT,
        
        /// <remarks/>
        INVALID,
        
        /// <remarks/>
        ACCEPT,
        
        /// <remarks/>
        PING,
        
        /// <remarks/>
        PROCESS,
        
        /// <remarks/>
        NOTIFY,
        
        /// <remarks/>
        FAILURE,
        
        /// <remarks/>
        CANCEL,
        
        /// <remarks/>
        STATE,
        
        /// <remarks/>
        PACKET,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smev.gosuslugi.ru/rev120315")]
    public partial class ServiceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mnemonicField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mnemonic {
            get {
                return this.mnemonicField;
            }
            set {
                this.mnemonicField = value;
                this.RaisePropertyChanged("Mnemonic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smev.gosuslugi.ru/rev120315")]
    public enum TypeCodeType {
        
        /// <remarks/>
        GSRV,
        
        /// <remarks/>
        GFNC,
        
        /// <remarks/>
        OTHR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestRequest", WrapperNamespace="http://smev.gosuslugi.ru/rev120315", IsWrapped=true)]
    public partial class Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smev.gosuslugi.ru/rev120315", Order=0)]
        public Client.Service.MessageType Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smev.gosuslugi.ru/rev120315", Order=1)]
        public Client.Service.MessageDataType MessageData;
        
        public Request() {
        }
        
        public Request(Client.Service.MessageType Message, Client.Service.MessageDataType MessageData) {
            this.Message = Message;
            this.MessageData = MessageData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://smev.gosuslugi.ru/rev120315", IsWrapped=true)]
    public partial class Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smev.gosuslugi.ru/rev120315", Order=0)]
        public Client.Service.MessageType Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://smev.gosuslugi.ru/rev120315", Order=1)]
        public Client.Service.MessageDataType MessageData;
        
        public Response() {
        }
        
        public Response(Client.Service.MessageType Message, Client.Service.MessageDataType MessageData) {
            this.Message = Message;
            this.MessageData = MessageData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmevBindingExtSeviceChannel : Client.Service.SmevBindingExtSevice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmevBindingExtSeviceClient : System.ServiceModel.ClientBase<Client.Service.SmevBindingExtSevice>, Client.Service.SmevBindingExtSevice {
        
        public SmevBindingExtSeviceClient() {
        }
        
        public SmevBindingExtSeviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmevBindingExtSeviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmevBindingExtSeviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmevBindingExtSeviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Service.Response Client.Service.SmevBindingExtSevice.DoWork(Client.Service.Request request) {
            return base.Channel.DoWork(request);
        }
        
        public void DoWork(ref Client.Service.MessageType Message, ref Client.Service.MessageDataType MessageData) {
            Client.Service.Request inValue = new Client.Service.Request();
            inValue.Message = Message;
            inValue.MessageData = MessageData;
            Client.Service.Response retVal = ((Client.Service.SmevBindingExtSevice)(this)).DoWork(inValue);
            Message = retVal.Message;
            MessageData = retVal.MessageData;
        }
        
        public System.Threading.Tasks.Task<Client.Service.Response> DoWorkAsync(Client.Service.Request request) {
            return base.Channel.DoWorkAsync(request);
        }
    }
}
